licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "auth_testing",
    hdrs = ["auth_testing.h"],
    deps = [
        "//trpc/auth",
        "@com_google_googletest//:gtest",
    ],
)
