licenses(["notice"])

package(default_visibility = ["//visibility:public"])

exports_files(["metrics.yaml"])

cc_library(
    name = "metrics_testing",
    hdrs = ["metrics_testing.h"],
    deps = [
        "//trpc/metrics",
    ],
)
