package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mock_session",
    srcs = [],
    hdrs = ["mock_session.h"],
    deps = [
        "//trpc/codec/grpc/http2:session",
        "@com_google_googletest//:gtest",
    ],
)
