# Description: trpc-cpp.

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "lightly_concurrent_hashmap",
    hdrs = ["lightly_concurrent_hashmap.h"],
    deps = [
        "//trpc/util/concurrency/detail:lightly_concurrent_hashmap_impl",
    ],
)