#!/bin/bash

./examples/helloworld/run.sh
./examples/features/admin/run.sh
./examples/features/fiber_forward/run.sh
./examples/features/future_forward/run.sh
./examples/features/grpc/run.sh
./examples/features/grpc_stream/run.sh
./examples/features/http/run.sh
./examples/features/http_async_upload_download/run.sh
./examples/features/http_rpc/run.sh
./examples/features/http_upload_download/run.sh
./examples/features/https/run.sh
./examples/features/request_dispatch/run.sh
./examples/features/rpcz/run.sh
./examples/features/thirdparty_protocol/run.sh
./examples/features/trpc_async_stream/run.sh
./examples/features/trpc_attachment/run.sh
./examples/features/trpc_compressor/run.sh
./examples/features/trpc_flatbuffers/run.sh
./examples/features/trpc_json/run.sh
./examples/features/trpc_noop/run.sh
./examples/features/trpc_stream/run.sh
./examples/features/trpc_stream_forward/run.sh
./examples/features/trpc_transparent/run.sh
