licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "server_transport_testing",
    hdrs = ["server_transport_testing.h"],
    deps = [
        "//trpc/transport/server:server_transport",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)
