licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "async_io",
    hdrs = ["async_io.h"],
    deps = [
        "//trpc/runtime/iomodel/async_io",
    ],
)
