licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "compressor_testing",
    hdrs = [
        "compressor_testing.h",
    ],
    deps = [
        "//trpc/compressor",
    ],
)
