licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "file_hasher",
    srcs = ["file_hasher.cc"],
    hdrs = ["file_hasher.h", "picosha2.h"],
    visibility = ["//visibility:public"],
)

