global:
  threadmodel:
    fiber:                            # Use Fiber(m:n coroutine) threadmodel
      - instance_name: fiber_instance # Need to be unique if you config mutiple fiber threadmodel instances
        # Fiber worker thread num
        # If not specified, will use number of cores on the machine.
        # In a Numa architecture, the workers will be automatically grouped (8-15 cores per group),
        # while in Uma architecture, they will not be grouped.
        concurrency_hint: 8
server:
  app: test
  server: forword
  admin_port: 8889
  admin_ip: 0.0.0.0
  service:
    - name: trpc.test.forword.Forward
      protocol: trpc
      network: tcp
      ip: 0.0.0.0
      port: 12346
  filter:
    - prometheus

client:
  service:
    - name: trpc.test.helloworld.Greeter
      target: 0.0.0.0:12345      
      protocol: trpc
      timeout: 1000
      network: tcp
      conn_type: long
      is_conn_complex: true
      selector_name: direct
  filter:
    - prometheus

plugins:
  metrics:
    prometheus:
      histogram_module_cfg:
        - 1
        - 5
        - 10
      const_labels:
        const_key1: const_value1
        const_key2: const_value2
      # push_mode:
      #   enable: true
      #   gateway_host: 127.0.0.1
      #   gateway_port: 9091
      #   job_name: trpc_prometheus_push_metrics
      #   interval_ms: 1000
  log:
    default:
      - name: default
        sinks:
          local_file:
            filename: forward_server.log
