# Description: trpc-cpp.

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "trpc_stream_testing",
    srcs = [],
    hdrs = ["trpc_stream_testing.h"],
    deps = [
        "//trpc/codec/trpc:trpc_protocol",
    ],
)
