# Description: trpc-cpp.

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "utils_help",
    srcs = ["utils_help.cc"],
    hdrs = ["utils_help.h"],
    deps = [
        "//trpc/naming/common:common_defs",
    ],
)
