licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "trpc_protocol_testing",
    hdrs = ["trpc_protocol_testing.h"],
    deps = [
        "//trpc/codec/trpc:trpc_protocol",
        "//trpc/serialization:serialization_factory",
        "//trpc/serialization:serialization_type",
        "//trpc/util:ref_ptr",
        "//trpc/util/buffer",
        "//trpc/util/flatbuffers:trpc_fbs",
    ],
)
