# Description: trpc-cpp.

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "power_of_two",
    srcs = ["power_of_two.cc"],
    hdrs = ["power_of_two.h"],
    deps = [
    ],
)

cc_library(
    name = "random",
    hdrs = ["random.h"],
)

cc_library(
    name = "hash",
    srcs = ["hash.cc"],
    hdrs = ["hash.h"],
    deps = [
        "//trpc/util/log:logging",
    ],
)
