licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "helper",
    srcs = ["helper.cc"],
    hdrs = ["helper.h"],
    deps = [
        "//examples/features/grpc_stream/server:stream_proto",
    ],
)
