licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mock_stream",
    srcs = [],
    hdrs = ["mock_stream.h"],
    deps = [
        "//trpc/stream/http/common:stream",
        "//trpc/stream/http/common:stream_handler",
        "@com_google_googletest//:gtest",
    ],
)
