licenses(["notice"])

package(
    default_visibility = [
        "//trpc:__subpackages__",
        "//test:__subpackages__",
    ]
)

proto_library(
    name = "trpc_proto",
    srcs = ["trpc.proto"],
    deps = [
        "@com_github_trpc_protocol//trpc:trpc_proto",
    ],
)
