licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mock_connection_testing",
    hdrs = ["mock_connection_testing.h"],
    deps = [
        "//trpc/runtime/iomodel/reactor/common:connection",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)
