title = "TOML TEST"

[owner]
name = "John Doe"
dob = "1979-05-27T07:32:00-08:00" # First-class dates

[database]
server = "127.0.0.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true

[servers]

# Indentation (tabs and/or spaces) is allowed but not required
[servers.alpha]
ip = "127.0.0.1"
dc = "eqdc10"

[servers.beta]
ip = "127.0.0.2"
dc = "eqdc10"
