licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "trpc_logging",
    hdrs = ["trpc_logging.h"],
    deps = [
        "//trpc/log:trpc_log",
    ],
)
