# trpc/util/http/sse/BUILD
cc_library(
    name = "http_sse",
    srcs = [
        "sse_parser.cc",
    ],
    hdrs = [
        "sse_event.h",
        "sse_parser.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//trpc/common:status",
    ],
)