licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mock_async_stream",
    srcs = [],
    hdrs = ["mock_async_stream.h"],
    deps = [
        "//trpc/stream/http/async:stream",
        "@com_google_googletest//:gtest",
    ],
)
